### ISSUE TITLE
What's the difference between YouTube-real and Celeb-real?

### ISSUE THREAD

**Issue by chenshen03** [yuezunli/celeb-deepfakeforensics#6]

**Comment by yuezunli** [comment]
YouTube-real is an extra real video set if you'd like to use it for
training.

**Comment by chenshen03** [comment]
Thank you.
In addition, can you provide the person ID of each video?
I want to split the dataset to ensure that the person IDs under different divisions are not repeated.

**Comment by yuezunli** [comment]
The id info is included in the name of each fake video. For example,
"aa_bb_cc.mp4", aa is the original id, bb is swapped id, cc is the video
index.

**Comment by chenshen03** [comment]
Thank you very much.
